server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: service-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config